spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-dry-sky-953847.us-east-2.aws.neon.tech/testes_db?user=AllysonAbreu&password=fXMRb04cuTtG&sslmode=require
    username: AllysonAbreu
    password: fXMRb04cuTtG

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345789}